### ISSUE TITLE
Duplication of logs forwarded from Azure Blob Storage by using officail Azure Function BlobForwarder

### ISSUE THREAD

**Issue by rmit-s3570641-yingzhi-lu** [newrelic/newrelic-azure-functions#29]
I created the blob forwarder and tested it. Everything works however it will send the entire blob content into New Relic. As a result, the blob trigger Azure Function will send the blob content again and again and logs are duplicated unexpectedly. (See attached document).

May I ask any suggestion for this? Duplicated logs are inconvenient to trace.
![screenshot](https://user-images.githubusercontent.com/21056942/103970270-eead4880-51bb-11eb-8f7d-48d9993c4c5b.png)

**Comment by jsubirat** [comment]
Hi @rmit-s3570641-yingzhi-lu , unfortunately the BlobForwarder function is not a forwarder per se, but a function to ingest a file in its current state as logs in New Relic. Therefore, it can not tail a given blob storage and send diffs only. As a result, if new lines are appended to the line, the whole file is sent over again.
